### ISSUE TITLE
Execution Expired on JRuby

### ISSUE THREAD

**Issue by jqr** [expectedbehavior/instrumental_agent#51]
A timeout exception is bubbling outside of the agent when trying to do DNS resolution. The scrubbed backtrace below is from an exception bubbling out of the agent running on JRuby 1.7.22 in 2.0 mode.

```
ERROR -- : Exception occurred: execution expired 
jruby-1.7.22/lib/ruby/2.0/resolv.rb:124:in `each_address' 
org/jruby/RubyArray.java:1613:in `each' 
jruby-1.7.22/lib/ruby/2.0/resolv.rb:119:in `each_address' 
jruby-1.7.22/lib/ruby/2.0/resolv.rb:106:in `getaddresses' 
jruby-1.7.22/lib/ruby/2.0/resolv.rb:55:in `getaddresses' 
shared/bundle/jruby/1.9/gems/instrumental_agent-0.13.4/lib/instrumental/agent.rb:275:in `ipv4_address_for_host' 
shared/bundle/jruby/1.9/gems/instrumental_agent-0.13.4/lib/instrumental/agent.rb:237:in `with_timeout' 
org/jruby/ext/timeout/Timeout.java:115:in `timeout' 
shared/bundle/jruby/1.9/gems/instrumental_agent-0.13.4/lib/instrumental/agent.rb:237:in `with_timeout' 
shared/bundle/jruby/1.9/gems/instrumental_agent-0.13.4/lib/instrumental/agent.rb:274:in `ipv4_address_for_host' 
shared/bundle/jruby/1.9/gems/instrumental_agent-0.13.4/lib/instrumental/agent.rb:371:in `start_connection_worker' 
shared/bundle/jruby/1.9/gems/instrumental_agent-0.13.4/lib/instrumental/agent.rb:290:in `send_command' 
shared/bundle/jruby/1.9/gems/instrumental_agent-0.13.4/lib/instrumental/agent.rb:136:in `increment' 
```

**Comment by JamesPaden** [comment]
Customer conversation: https://app.intercom.io/a/apps/258zoi0n/inbox/all/conversations/4410458870
